= ovrvnc - VNC Viewer for Oculus Go

WIP.

ovrvnc recently switched to TigerVNC as a core library and supports continuous
updates and asynchronous event sending, which improves throughput and latency
drastically but might be unstable for now (although it works well on my PC).

== Install prebuilt binary

Download link:http://mimosa-pudica.net/tmp/ovrvnc-release.apk[ovrvnc-release.apk] .

----
$ adb uninstall net.mimosa_pudica.ovrvnc
$ adb install ovrvnc-release.apk
$ vi ovrvnc.toml # configure host, password, etc.  See below.
$ adb push ovrvnc.toml /sdcard/
----

Note for Xorg users: x0vncserver >= 1.9 bundled in TigerVNC with following
arguments is recommended.
----
x0vncserver --comparefb=1 --maxprocessorusage=100
----

Note for Windows users: UltraVNC does not seem to support continuous updates
thus slow but I don't know other alternatives (TigerVNC server on Windows seems
broken).  Using "Poll Full Screen" and "Desktop Duplication" options improves
the performance (I don't know this configuration is the best).

See also link:http://github.com/y-fujii/mfxvnc/[mfxvnc] .

== Configuration

Minimal example of `/sdcard/ovrvnc.toml`:
----
[[screens]]
host = "hogehoge"
----

More complex example:
----
#color_bg = [0.0, 0.0, 0.0]

[[screens]]
host = "192.168.179.5"
#port = 5900
#password = ""
latitude  = -15.0
#longitude = 0.0
#lossy = true

[[screens]]
host = "192.168.179.4"
#port = 5900
password = "hogehoge"
latitude  = -15.0
longitude = 180.0
#lossy = true
----

== Build

XXX: Apply patches.
----
export     ANDROID_HOME=...
export ANDROID_NDK_HOME=...
export  OCULUS_SDK_PATH=...

cd thirdparty/libjpeg-turbo
./build.sh
cd ../..
make
----
